---
title: "Student Crimtab Data Graphic Analysis"
author: "coop711"
date: "2015년 3월 25일"
output: html_document
---

Data Manipulation
-----------------

- Data Frame으로 정리하고, 다시 long format 으로 변환. `height`를 인치로 변환하면 어떻게 될까?

```{r}
dimnames(crimtab.2)[[2]]<-as.numeric(dimnames(crimtab.2)[[2]])/2.54
crimtab.2
crimtab.3<-crimtab.2
crimtab.3.df<-as.data.frame(crimtab.3, stringsAsFactors = F)
head(crimtab.3.df)
str(crimtab.3.df)
crimtab.3.df$finger<-as.numeric(crimtab.3.df$Var1)
crimtab.3.df$height<-as.numeric(crimtab.3.df$Var2)
str(crimtab.3.df)
crimtab.3.long<-apply(crimtab.3.df[,4:5], 2, function(x) rep(x, crimtab.3.df[,3]))
str(crimtab.3.long)
```

- `function(x) rep(x, crimtab.3.df[,3])` 이 어렵게 느껴지면 다음과 같이 세 단계로 나누어 작업할 수도 있음.

```{r}
attach(crimtab.3.df)
finger.long<-rep(finger, Freq)
height.long<-rep(height, Freq)
crimtab.3.long.2<-data.frame(finger=finger.long, height=height.long)
str(crimtab.3.long.2)
detach()
```

- 산점도를  여러 유형으로 표현하기 위하여 필요한 패키지 설치

```
install.packages("hexbin")
```

```{r}
library(hexbin)
```

```{r}
crimtab.bin<-hexbin(crimtab.3.long[,"height"],crimtab.3.long[,"finger"], xbins=50)
```


```{r fig.width=8, fig.height=8}
par(mfrow=c(2,2))
plot(finger~height, data=crimtab.3.long)
plot(finger~height, data=crimtab.3.long, pch=20)
smoothScatter(crimtab.3.long[,"height"], crimtab.3.long[,"finger"], xlab="height", ylab="finger")
smoothScatter(crimtab.3.long[,"height"], crimtab.3.long[,"finger"], nbin=32, xlab="height", ylab="finger")
```

```{r fig.width=6, fig.height=6}
par(mfrow=c(1,1))
plot(crimtab.bin, xlab="height(inches)", ylab="finger length(cm)")
```

- 산점도와 함께 주변분포 표시

```{r fig.width=6, fig.height=6}
par(mar=c(4,4,1,1))
par(fig=c(0,0.8,0,0.8))
plot(finger~height, data=crimtab.3.long, pch=20)
par(fig=c(0,0.8,0.68,1), new=TRUE)
hist(crimtab.3.long[,"height"], axes=F, ann=F)
par(fig=c(0.68,1,0,0.8), new=TRUE)
barplot(table(cut(crimtab.3.long[,"finger"], breaks=10)), space=0, col="white", horiz=T, axes=F, axisnames=F)
par(fig=c(0,1,0,1))
par(mar=c(5,4,1,1)+0.1)
```

- `persp()`를 활용하면 다양한 각도에서 3차원 겨냥도를 그려볼 수 있음. $x$ 축은 행, $y$ 축은 열에 펼쳐진 격자를 0에서 1까지로 조정. `theta`와 `phi`는 박스를 돌려보는 각도이고, `expand`는 박스 높이의 상대적인 비율임. $x$ 축과 $y$ 축의 라벨 이외에는 디폴트값을 적용시킨 겨냥도와 적절히 조정한 겨냥도를 비교해 볼 것,

```{r fig.width=12, fig.height=12}
par(mfrow=c(2,2))
persp(crimtab.3, xlab="Finger Length", ylab="Height")
persp(crimtab.3, xlab="Finger Length", ylab="Height", theta=90, phi=30, expand=0.5, scale=TRUE)
persp(crimtab.3, xlab="Finger Length", ylab="Height", theta=135, phi=30, expand=0.5, scale=TRUE)
persp(crimtab.3, xlab="Finger Length", ylab="Height", theta=45, phi=45, expand=0.5, scale=TRUE)
par(mfrow=c(1,1))
```

